server:
  port: 9091  # Définit le port de ton serveur Spring Boot

spring:
  application:
    name: SESSION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3307/session_service_db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: # create    update
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL du serveur Eureka
    fetch-registry: true # Pour récupérer les services enregistrés
    register-with-eureka: true # Pour s'enregistrer dans Eureka
  instance:
    hostname: localhost # Nom d'hôte (modifiable si nécessaire)
    prefer-ip-address: true # Utiliser l'adresse IP au lieu du nom d'hôte

logging:
  level:
    org.springframework.web: DEBUG
