server:
  port: 9091  # Définit le port de ton serveur Spring Boot

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/session_service_db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: # create    update
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.web: DEBUG
